baseURL = "https://lalalavir.github.io/cutlass_study/"
languageCode = "zh-cn"
title = "Cutlass Study Blog"
theme = "relearn"

[outputs]
home = ["HTML", "RSS", "SEARCH"]

[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  themeVariant = "olive-gray-green"
  disableSearchHiddenPages = true
  disableLandingPageButton = true
