baseURL = "https://lalalavir.github.io/cutlass_study/"
title = "Cutlass Study Blog"
theme = "relearn"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "RSS", "SEARCH"]

[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        inline = [['\(', '\)'], ['$', '$']]
        block  = [['\[', '\]'], ['$$', '$$']]
[params]
  math.force = true
  themeVariant = "olive-gray-green"
  disableSearchHiddenPages = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = false

[params.giscus]
  enable = true
  repo = "lalalavir/cutlass_study"
  repoId = "R_kgDORSF6jw"
  category = "General"
  categoryId = "DIC_kwDORSF6j84C2qaZ"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  collapsible = true
  initiallyOpen = true
  toggleLabel = "评论区"

[languages]
  [languages.zh]
    weight = 1
    languageCode = "zh-CN"
    languageName = "中文"
    title = "Cutlass 学习博客"
    contentDir = "content/zh"
    [languages.zh.params]
      landingPageName = "首页"

  [languages.en]
    weight = 2
    languageCode = "en-US"
    languageName = "English"
    title = "Cutlass Study Blog"
    contentDir = "content/en"
    [languages.en.params]
      landingPageName = "Home"

[[languages.zh.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = "GitHub Star"
  url = "https://github.com/lalalavir/cutlass_study"
  weight = 10

[[languages.en.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = "GitHub Star"
  url = "https://github.com/lalalavir/cutlass_study"
  weight = 10

