baseURL = "https://lalalavir.github.io/cutlass_study/"
title = "Cutlass Study Blog"
theme = "relearn"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[outputs]
home = ["HTML", "RSS", "SEARCH"]

[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  themeVariant = "olive-gray-green"
  disableSearchHiddenPages = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = false

[languages]
  [languages.zh]
    weight = 1
    languageCode = "zh-CN"
    languageName = "中文"
    title = "Cutlass 学习博客"
    contentDir = "content/zh"
    [languages.zh.params]
      landingPageName = "首页"

  [languages.en]
    weight = 2
    languageCode = "en-US"
    languageName = "English"
    title = "Cutlass Study Blog"
    contentDir = "content/en"
    [languages.en.params]
      landingPageName = "Home"
